models_dict = {
    "MLPRegressor": "sklearn.neural_network",
    "Lasso": "sklearn.linear_model",
    "SVR": "sklearn.svm",
    "ElasticNet": "sklearn.linear_model",
    "Ridge": "sklearn.linear_model",
    "GradientBoostingRegressor": "sklearn.ensemble",
    "RandomForestRegressor":"sklearn.ensemble",
    "DecisionTreeRegressor":"sklearn.tree",
    "LogisticRegression": "sklearn.linear_model",
    "XGBRegressor": "xgboost",
    "MLP": 'chemml.models',
    "LGBMRegressor": "lightgbm",
    "RandomForestClassifier": "sklearn.ensemble",
    "MLPClassifier": "sklearn.neural_network",
    "DecisionTreeClassifier": "sklearn.tree",
    "SVC": "sklearn.svm",
    "KNeighborsClassifier": "sklearn.neighbors",
    "LGBMClassifier": "lightgbm",
    "XGBClassifier": "xgboost",
        
}